-- One-time: set BOOKNO=9 on transfer bills that were created with BOOKNO=1.
-- Run on each site (KSS HQ / kss-pc SYP) against PARTS9.

SET XACT_ABORT ON;
BEGIN TRAN;

UPDATE dbo.SIMAS
SET BOOKNO = '9'
WHERE BOOKNO <> '9'
  AND (
    BILLNO LIKE 'TF%'
    OR BILLNO LIKE '3TF%'
  );

UPDATE dbo.PIMAS
SET BOOKNO = '9'
WHERE BOOKNO <> '9'
  AND (
    BILLNO LIKE 'TF%'
    OR BILLNO LIKE '3TF%'
  );

COMMIT TRAN;

SELECT 'SIMAS' AS tbl, BILLNO, BOOKNO FROM dbo.SIMAS
WHERE BILLNO LIKE 'TF%' OR BILLNO LIKE '3TF%'
ORDER BY BILLNO;

SELECT 'PIMAS' AS tbl, BILLNO, BOOKNO FROM dbo.PIMAS
WHERE BILLNO LIKE 'TF%' OR BILLNO LIKE '3TF%'
ORDER BY BILLNO;
